### ISSUE TITLE
result file 0kb

### ISSUE THREAD

**Issue by nguyenvanduc543** [Underneach/Nicotine-String-Sorter#1]
i add 4 request, a request found 45 line but result file is 0kb, is it error?

**Comment by Underneach** [comment]
> i add 4 request, a request found 45 line but result file is 0kb, is it error?

are you use last version?

**Comment by nguyenvanduc543** [comment]
> > i add 4 request, a request found 45 line but result file is 0kb, is it error?
> 
> are you use last version?

yeah i use ver 2.4.1

**Comment by Underneach** [comment]
2.6.0 FIX
