### ISSUE TITLE
Разделитель

### ISSUE THREAD

**Issue by Moderator199** [Underneach/Nicotine-String-Sorter#3]
Пробел в строке приводит к занесению строки в невалид
Пример:
url login:pass
url login:pass
url login:pass
url:login:pass
url:login:pass
url:login:pass

3 первые строки будут удалены в конечном файле, есть файлы где разные разделители в одном файле, например пробел и :

**Comment by Underneach** [comment]
Делать лично под твой материал настройку я не буду, >90% баз имеют формат u:l:p
